### PR TITLE
fix: ZH translation for page size selector

### LINKED ISSUE #26: zh (PRC) translation is wrong
image

### PR DESCRIPTION
**Pull request by bemailloux**
Fixes #26 

Before
image

After
image

### CODE REVIEW

**Comment by anhill-D2L** [comment]
Side thought: would visual diffs in other languages add any value?

**Review by anhill-D2L — APPROVED** [review]

**Comment by bemailloux** [comment]
> Side thought: would visual diffs in other languages add any value?

Maybe, especially on a small component such as this? This repo doesn't have visual diffs enabled at all at the moment though.

File: lang/zh.js [hunk 1]
```diff
@@ -3,6 +3,6 @@
 export default {
 	page_next : "下一页",
 	page_previous : "上一页",
-	page_size_option : "每页 {Count} 个结果",
+	page_size_option : "每页 {count} 个结果",
```
Comment (dlockhart) [inline lang/zh.js:6]: Ugh, maybe one day we'll have some kind of linting hooked into the translation process to catch this kind of thing before it gets into our code. 🙏
